import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One sidebar per audience. Listed by hand rather than autogenerated: the order is an argument
 * rather than an accident, and a list here fails the build when a page is renamed instead of quietly
 * moving it.
 */
const sidebars: SidebarsConfig = {
    run: ['quick-start'],
};

export default sidebars;
