import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One sidebar per audience, because they share no pages: somebody running a server, and somebody
 * writing an engine or a client.
 *
 * The hand-written sections are listed by hand rather than autogenerated: the order is an argument rather than an accident, and a
 * list here fails the build when a page is renamed instead of quietly moving it. Most of these pages
 * are copied in by `scripts/docs.sync.mjs`; their ids are the `doc` paths in its list.
 */
const sidebars: SidebarsConfig = {
    run: [
        'quick-start',
        'operating',
        {
            type: 'category',
            label: 'Engines',
            link: { type: 'doc', id: 'engines/index' },
            collapsed: false,
            items: ['engines/kokoro', 'engines/chatterbox', 'engines/orpheus', 'engines/dia', 'engines/tone'],
        },
        'openai',
        'mcp',
        'help',
    ],
    build: ['develop/index', 'protocol', 'develop/worker-sdk', 'develop/conformance', 'develop/contributing'],
    // Regenerated from the contracts by `pnpm codegen`, so nobody here chooses what is in it: it is
    // autogenerated from the directory and takes its order from the `_category_.json` files.
    api: [{ type: 'autogenerated', dirName: 'api-reference' }],
};

export default sidebars;
