# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field

class Dial(BaseModel):
    # Inclusive.
    min: float
    # Inclusive.
    max: float
    # What the engine uses when the request says nothing.
    default: float

class Cloning(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    supported: bool
    # [min, max] of usable reference audio.
    reference_seconds: list[float] | None = Field(alias="referenceSeconds", default=None)
    formats: list[str] | None = None

class Streaming(BaseModel):
    supported: bool
    granularity: Literal["chunk", "sentence"] | None = None

class NativeFormat(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # v1 accepts pcm_s16le and nothing else.
    encoding: str
    sample_rate: int = Field(alias="sampleRate")
    channels: int

class EngineIdentity(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str = Field(alias="displayName")
    adapter_version: str = Field(alias="adapterVersion")
    upstream_version: str | None = Field(alias="upstreamVersion", default=None)

# Code and weights separately, because the weights licence is the one package metadata never reveals
# and the one that decides whether a commercial user may ship. A scanner reads the package, reports
# the code licence, and is wrong in the way that matters.
class License(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    code: str
    weights: str
    weights_commercial_use: bool = Field(alias="weightsCommercialUse")
    notes: str | None = None

class Device(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    type: Literal["cuda", "rocm", "mps", "cpu"]
    name: str
    vram_bytes: int | None = Field(alias="vramBytes", default=None)

class Voice(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    label: str
    description: str | None = None
    # Opaque. Changes whenever the rendering would. Never parse it.
    spec: str
    tags: list[str] | None = None
    # Worker-scoped; the core rewrites it on the way out.
    preview_url: str | None = Field(alias="previewUrl", default=None)

class CreateVoiceForm(BaseModel):
    id: str
    label: str | None = None
    reference: bytes

class SpeakRequest(BaseModel):
    text: str
    voice: str | None = None
    # Absent means whatever is loaded.
    variant: str | None = None
    format: Literal["wav", "mp3", "opus", "flac", "pcm"] | None = None
    # From the effective variant's `languages`.
    language: str | None = None
    # Closed, and deliberately has no word for "ordinary".
    delivery: Literal["hushed", "frantic"] | None = None
    # Validated against the effective variant's dials.
    params: dict[str, float] | None = None
    seed: int | None = None
    stream: bool | None = None

class LoadRequest(BaseModel):
    variant: str | None = None

# `retryable` is a field rather than something the client infers from the status, because the
# distinction that matters is between "this request was wrong" and "this request was fine and the
# server was not". A caller that conflates them either retries a permanent failure forever or
# discards work that would have succeeded on the next pass.
class ErrorDetail(BaseModel):
    # A closed set that § 9 grows at the end. A reader that meets a code from a newer contract must
    # not lose the envelope over it: `message` and `retryable` are the two fields that decide what
    # the caller does next, and they parse fine. The core falls back to `internal` for the code and
    # keeps the rest, rather than reporting a parse failure in place of the real error.
    code: Literal["bad_request", "unknown_engine", "unknown_voice", "unsupported", "model_unavailable", "oom", "overloaded", "internal"]
    message: str
    retryable: bool

class WorkerHealth(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    process: Literal["up", "draining"]
    model: Literal["unloaded", "loading", "loaded", "unloading"]
    variant: str | None = None
    device: str | None = None
    vram_bytes: int | None = Field(alias="vramBytes", default=None)

class ResidencySummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    resident: int
    max: int
    waiting: int
    # Named, because a wait at maxResidentModels 1 looks exactly like a hang.
    blocked_by: str | None = Field(alias="blockedBy", default=None)

# What one build of an engine can perform. Capabilities depend on which build is loaded, which is
# the whole reason this document has two levels: chatterbox `turbo` performs the paralinguistic
# tags and discards the dials, while `original` is the other way round.
class Variant(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # A subset of the standard vocabulary, § 5.
    cues: list[str]
    # Ditto. Not an enum: § 9 forbids failing on an unknown one.
    deliveries: list[str]
    # Engine-specific numbers, named by the adapter.
    dials: dict[str, Dial]
    languages: list[str] | None = None
    # Overrides the engine's own ceiling for this build.
    max_characters: int | None = Field(alias="maxCharacters", default=None)

class EngineSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str = Field(alias="displayName")
    license: License
    process: Literal["down", "starting", "up", "draining", "failed"]
    model: Literal["unloaded", "loading", "loaded", "unloading"]
    variant: str | None = None
    last_error: str | None = Field(alias="lastError", default=None)
    restarts: int

class EngineSpeakRequest(SpeakRequest):
    engine: str

class ErrorBody(BaseModel):
    error: ErrorDetail

# The resident build, and everything true only while it is resident. Absent from the capability
# document entirely when nothing is loaded, because a worker in up(unloaded) has nothing to
# describe and an invented answer is worse than no answer.
class CurrentVariant(Variant):
    model_config = ConfigDict(populate_by_name=True)

    variant: str
    cloning: Cloning
    streaming: Streaming
    native_format: NativeFormat = Field(alias="nativeFormat")

class CoreHealth(BaseModel):
    contract: int
    status: Literal["ok", "degraded"]
    engines: list[EngineSummary]
    residency: ResidencySummary

class Capabilities(BaseModel):
    # The contract major this worker settled on. § 9.
    contract: int
    engine: EngineIdentity
    license: License
    device: Device
    current: CurrentVariant | None = None
    variants: dict[str, Variant]
    # What this worker can actually encode, here and now.
    formats: list[str]
