# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
"""Contract scalars whose JSON form differs from their Python type."""
from __future__ import annotations

from typing import Annotated, Any

from pydantic import BeforeValidator, PlainSerializer


def _parse_bigint(value: Any) -> Any:
    # "123n" is the TypeScript SDK's form, "123" the other SDKs', and a number whatever else a
    # server might send.
    if isinstance(value, str):
        text = value.strip()
        return int(text[:-1] if text.endswith("n") else text)
    return value


# A contract bigint: an int in Python, and a digit string in JSON, which keeps its precision past
# 2**53 and is what a ContractKit server accepts.
BigInt = Annotated[int, BeforeValidator(_parse_bigint), PlainSerializer(str, return_type=str, when_used="json")]
