# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from ._base_client import BaseClient, SdkError
from ._client_rhapsode_worker import RhapsodeWorkerClient
from ._client_rhapsode_public import RhapsodePublicClient


class Sdk(BaseClient):
    def __init__(self, base_url: str, headers: dict[str, str] | None = None):
        super().__init__(base_url, headers)
        self.rhapsodeWorker = RhapsodeWorkerClient(base_url, headers)
        self.rhapsodePublic = RhapsodePublicClient(base_url, headers)

__all__ = ["BaseClient", "SdkError", "Sdk", "RhapsodeWorkerClient", "RhapsodePublicClient"]
