# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

import httpx
from collections.abc import Mapping
from typing import Any

from pydantic import BaseModel
from pydantic_core import to_jsonable_python


def _wire_values(values: Mapping[str, Any] | BaseModel | None) -> dict[str, Any]:
    """Query or header values in the JSON forms the server's schemas parse, unset ones left out.

    A model (a `query:` or `headers:` declared as a model ref) is dumped by contract name with the
    flags a request body uses. A mapping (the TypedDict of an inline block) holds Python values,
    which httpx would str(): a datetime into "2026-01-02 03:04:00+00:00", which no ISO 8601 parser
    accepts, and None into an empty string.
    """
    if values is None:
        return {}
    if isinstance(values, BaseModel):
        data = values.model_dump(mode="json", by_alias=True, exclude_unset=True)
    else:
        data = to_jsonable_python(dict(values))
    # Neither a query string nor a header can say null, so a None is sent as nothing at all.
    return {key: value for key, value in data.items() if value is not None}


def _header_text(value: Any) -> str:
    """A header value as text, which is all httpx accepts: booleans as the router parses them."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return ",".join(_header_text(item) for item in value)
    return str(value)


class SdkError(Exception):
    def __init__(self, status: int, status_text: str, body: Any):
        super().__init__(f"{status} {status_text}")
        self.status = status
        self.status_text = status_text
        self.body = body


class BaseClient:
    def __init__(self, base_url: str, headers: dict[str, str] | None = None):
        self._base_url = base_url.rstrip("/")
        self._headers = headers or {}
        self._http = httpx.AsyncClient()
        self._last_status = 0
        self._last_content_type = ""

    async def _fetch(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: Mapping[str, Any] | BaseModel | None = None,
        extra_headers: Mapping[str, Any] | BaseModel | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> Any:
        result, _ = await self._fetch_with_headers(
            path,
            method=method,
            body=body,
            params=params,
            extra_headers=extra_headers,
            content_type=content_type,
            body_kind=body_kind,
            response_kind=response_kind,
            expect_statuses=expect_statuses,
        )
        return result

    async def _fetch_full(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: Mapping[str, Any] | BaseModel | None = None,
        extra_headers: Mapping[str, Any] | BaseModel | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> tuple[int, str, Any, dict[str, str]]:
        """Like _fetch_with_headers, but also reports the status and content type.

        Used by operations that declare more than one status, or more than one mime for a
        status, where the caller cannot know which it got without being told.
        """
        result, headers = await self._fetch_with_headers(
            path,
            method=method,
            body=body,
            params=params,
            extra_headers=extra_headers,
            content_type=content_type,
            body_kind=body_kind,
            response_kind=response_kind,
            expect_statuses=expect_statuses,
        )
        return self._last_status, self._last_content_type, result, headers

    async def _fetch_with_headers(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: Mapping[str, Any] | BaseModel | None = None,
        extra_headers: Mapping[str, Any] | BaseModel | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> tuple[Any, dict[str, str]]:
        headers = {**self._headers, **{key: _header_text(value) for key, value in _wire_values(extra_headers).items()}}
        # multipart is the exception: httpx has to generate the boundary itself, and it can only
        # do that if it owns the Content-Type header. Setting it here would produce a header with
        # no boundary parameter, which no server can parse.
        if body is not None and body_kind != "multipart":
            headers["Content-Type"] = content_type or "application/json"
        # body_kind controls how httpx serializes the request body:
        #   "json"      — a JSON-serializable object, sent via httpx's json= kwarg
        #   "form"      — a mapping sent as application/x-www-form-urlencoded via data=
        #   "multipart" — a mapping of file parts sent via files=, boundary generated by httpx
        #   "text"/"binary" — a raw str/bytes payload, sent via content= unchanged
        request_kwargs: dict[str, Any] = {"method": method, "url": f"{self._base_url}{path}", "params": _wire_values(params), "headers": headers}
        if body is not None:
            if body_kind == "json":
                request_kwargs["json"] = body
            elif body_kind == "form":
                request_kwargs["data"] = body
            elif body_kind == "multipart":
                request_kwargs["files"] = body
            else:
                request_kwargs["content"] = body
        response = await self._http.request(**request_kwargs)
        # expect_statuses carries the codes this operation declares as values rather than
        # errors — a 304 from conditional-GET middleware, or an error status the service
        # returns deliberately. Anything else outside 2xx still raises.
        if not response.is_success and response.status_code not in expect_statuses:
            try:
                error_body = response.json()
            except Exception:
                error_body = response.text
            raise SdkError(response.status_code, response.reason_phrase, error_body)
        # HTTP headers are case-insensitive — normalize to lowercase keys for stable lookup.
        response_headers = {k.lower(): v for k, v in response.headers.items()}
        self._last_status = response.status_code
        self._last_content_type = response.headers.get("content-type", "").split(";")[0].strip()
        if response.status_code == 204 or not response.content:
            return None, response_headers
        # "auto" is for a status declaring several mimes that do not read the same way: the
        # response itself is the only thing that knows which one came back.
        kind = response_kind
        if kind == "auto":
            ct = self._last_content_type
            if ct.startswith("text/"):
                kind = "text"
            elif ct == "application/json" or ct.endswith("+json"):
                kind = "json"
            else:
                kind = "binary"
        if kind == "text":
            return response.text, response_headers
        if kind == "binary":
            return response.content, response_headers
        return response.json(), response_headers
