# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from urllib.parse import quote
from typing import Any, Literal, TypedDict
from pydantic import TypeAdapter
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_rhapsode_types import Capabilities, CreateVoiceForm, ErrorBody, FetchRequest, LoadRequest, SpeakRequest, Voice, WorkerHealth


class WorkerCreateVoice201Response(TypedDict):
    status: Literal[201]
    content_type: Literal["application/json"]
    data: Voice


class WorkerCreateVoice400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerCreateVoice422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerDeleteVoice204Response(TypedDict):
    status: Literal[204]


class WorkerDeleteVoice400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerDeleteVoice404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerDeleteVoice422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerVoicePreview200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav"]
    data: bytes


class WorkerVoicePreview404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerLoad200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: WorkerHealth


class WorkerLoad503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerFetch204Response(TypedDict):
    status: Literal[204]


class WorkerFetch400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerFetch422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerFetch429Response(TypedDict):
    status: Literal[429]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerFetch500Response(TypedDict):
    status: Literal[500]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerSpeak200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav", "audio/mpeg", "audio/opus", "audio/flac", "audio/l16"]
    data: bytes


class WorkerSpeak400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerSpeak404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerSpeak422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerSpeak429Response(TypedDict):
    status: Literal[429]
    content_type: Literal["application/json"]
    data: ErrorBody


class WorkerSpeak503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


_WORKER_VOICES_RESPONSE: TypeAdapter[list[Voice]] = TypeAdapter(list[Voice])


class RhapsodeWorkerClient(BaseClient):

    async def worker_health(self) -> WorkerHealth:
        """
        Answers while unloaded, and while draining.
        """
        result = await self._fetch("/health", method="GET")
        return WorkerHealth.model_validate(result)

    async def worker_capabilities(self) -> Capabilities:
        result = await self._fetch("/capabilities", method="GET")
        return Capabilities.model_validate(result)

    async def worker_voices(self) -> list[Voice]:
        result = await self._fetch("/voices", method="GET")
        return _WORKER_VOICES_RESPONSE.validate_python(result)

    async def worker_create_voice(self, body: dict[str, Any]) -> WorkerCreateVoice201Response | WorkerCreateVoice400Response | WorkerCreateVoice422Response:
        """
        Cloning, where the variant supports it.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/voices", method="POST", body=body, content_type="multipart/form-data", body_kind="multipart", response_kind="auto", expect_statuses=(400, 422))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 201, "content_type": "application/json", "data": Voice.model_validate(result) }

    async def worker_delete_voice(self, voice: str) -> WorkerDeleteVoice204Response | WorkerDeleteVoice400Response | WorkerDeleteVoice404Response | WorkerDeleteVoice422Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/voices/{quote(str(voice), safe='')}", method="DELETE", response_kind="auto", expect_statuses=(400, 404, 422))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 204 }

    async def worker_voice_preview(self, voice: str) -> WorkerVoicePreview200Response | WorkerVoicePreview404Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/voices/{quote(str(voice), safe='')}/preview", method="GET", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "audio/wav", "data": result }

    async def worker_load(self, body: LoadRequest) -> WorkerLoad200Response | WorkerLoad503Response:
        _status, _content_type, result, _response_headers = await self._fetch_full("/load", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(503,))
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": WorkerHealth.model_validate(result) }

    async def worker_unload(self) -> WorkerHealth:
        """
        Idempotent, and never fatal. Unloading nothing is a success.
        """
        result = await self._fetch("/unload", method="POST")
        return WorkerHealth.model_validate(result)

    async def worker_terminate(self) -> None:
        """
        Drain and exit 0. The answer goes out before the process does, so 202 rather than 200:
        """
        result = await self._fetch("/terminate", method="POST")
        return None

    async def worker_fetch(self, body: FetchRequest) -> WorkerFetch204Response | WorkerFetch400Response | WorkerFetch422Response | WorkerFetch429Response | WorkerFetch500Response:
        """
        Download a variant's weights without loading them, so a first /speak does not sit through
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/fetch", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 422, 429, 500))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 429:
            return { "status": 429, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 500:
            return { "status": 500, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 204 }

    async def worker_speak(self, body: SpeakRequest) -> WorkerSpeak200Response | WorkerSpeak400Response | WorkerSpeak404Response | WorkerSpeak422Response | WorkerSpeak429Response | WorkerSpeak503Response:
        """
        Loads on demand. It does not fail with \"no model loaded\" and does not require /load first.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/speak", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 404, 422, 429, 503))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 429:
            return { "status": 429, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _content_type == "audio/mpeg":
            return { "status": 200, "content_type": "audio/mpeg", "data": result }
        if _content_type == "audio/opus":
            return { "status": 200, "content_type": "audio/opus", "data": result }
        if _content_type == "audio/flac":
            return { "status": 200, "content_type": "audio/flac", "data": result }
        if _content_type == "audio/l16":
            return { "status": 200, "content_type": "audio/l16", "data": result }
        return { "status": 200, "content_type": "audio/wav", "data": result }
