# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from urllib.parse import quote
from typing import Any, Literal, NotRequired, TypedDict
from pydantic import TypeAdapter
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_rhapsode_public import OpenApiDocument, Settings, SettingsPatch
from ._models_rhapsode_types import Capabilities, CatalogEntry, CoreHealth, CreateVoiceForm, EngineDialogueRequest, EngineSpeakRequest, EngineSummary, ErrorBody, InstallJob, PullRequest, ReinstallOutdated, ResidencyDetail, UpdateStatus, Voice


UnloadEngineQuery = TypedDict("UnloadEngineQuery", {
    "mode": NotRequired[Literal["terminate", "unload"]],
})


InstallEngineQuery = TypedDict("InstallEngineQuery", {
    "pull": NotRequired[str],
    "accept": NotRequired[str],
})


ReinstallEngineQuery = TypedDict("ReinstallEngineQuery", {
    "accept": NotRequired[str],
})


class EngineCapabilities200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: Capabilities


class EngineCapabilities404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class EngineCapabilities503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


class EngineVoices200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: list[Voice]


class EngineVoices404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice201Response(TypedDict):
    status: Literal[201]
    content_type: Literal["application/json"]
    data: Voice


class CreateVoice400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class DeleteVoice204Response(TypedDict):
    status: Literal[204]


class DeleteVoice400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class DeleteVoice403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class DeleteVoice404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class DeleteVoice422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class VoicePreview200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav"]
    data: bytes


class VoicePreview404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav", "audio/mpeg", "audio/opus", "audio/flac", "audio/l16"]
    data: bytes


class Speak400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak429Response(TypedDict):
    status: Literal[429]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


class Dialogue200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav", "audio/mpeg", "audio/opus", "audio/flac", "audio/l16"]
    data: bytes


class Dialogue400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class Dialogue404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Dialogue422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class Dialogue429Response(TypedDict):
    status: Literal[429]
    content_type: Literal["application/json"]
    data: ErrorBody


class Dialogue503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


class UninstallEngine204Response(TypedDict):
    status: Literal[204]


class UninstallEngine403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class UninstallEngine404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class UninstallEngine409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class UnloadEngine200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: EngineSummary


class UnloadEngine403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class UnloadEngine404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class UnloadEngine409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallEngine202Response(TypedDict):
    status: Literal[202]
    content_type: Literal["application/json"]
    data: InstallJob


class InstallEngine400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallEngine403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallEngine404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallEngine409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class ReinstallEngine202Response(TypedDict):
    status: Literal[202]
    content_type: Literal["application/json"]
    data: InstallJob


class ReinstallEngine400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class ReinstallEngine403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class ReinstallEngine404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class ReinstallEngine409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class PullEngine202Response(TypedDict):
    status: Literal[202]
    content_type: Literal["application/json"]
    data: InstallJob


class PullEngine403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class PullEngine404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class PullEngine409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallJobs200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: list[InstallJob]


class InstallJobs403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class ReinstallOutdated202Response(TypedDict):
    status: Literal[202]
    content_type: Literal["application/json"]
    data: ReinstallOutdated


class ReinstallOutdated403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallJob200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: InstallJob


class InstallJob403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallJob404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallJobEvents200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["text/event-stream"]
    data: str


class InstallJobEvents403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class InstallJobEvents404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Settings200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: Settings


class Settings403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class UpdateSettings200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: Settings


class UpdateSettings400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class UpdateSettings403Response(TypedDict):
    status: Literal[403]
    content_type: Literal["application/json"]
    data: ErrorBody


class UpdateSettings404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class UpdateSettings409Response(TypedDict):
    status: Literal[409]
    content_type: Literal["application/json"]
    data: ErrorBody


class UpdateSettings422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


_ENGINES_RESPONSE: TypeAdapter[list[EngineSummary]] = TypeAdapter(list[EngineSummary])
_ENGINE_VOICES_RESPONSE_200: TypeAdapter[list[Voice]] = TypeAdapter(list[Voice])
_CATALOG_RESPONSE: TypeAdapter[list[CatalogEntry]] = TypeAdapter(list[CatalogEntry])
_INSTALL_JOBS_RESPONSE_200: TypeAdapter[list[InstallJob]] = TypeAdapter(list[InstallJob])


class RhapsodePublicClient(BaseClient):

    async def health(self) -> CoreHealth:
        """
        Health
        The core's own health, which answers even while every worker is down.
        """
        result = await self._fetch("/health", method="GET")
        return CoreHealth.model_validate(result)

    async def update_status(self) -> UpdateStatus:
        """
        Update status
        Whether a newer rhapsode has been released, from a check made at most once a day.
        """
        result = await self._fetch("/update", method="GET")
        return UpdateStatus.model_validate(result)

    async def check_for_update(self) -> UpdateStatus:
        """
        Check for an update
        Asks GitHub for the latest release now, and answers once it has.
        """
        result = await self._fetch("/update/check", method="POST")
        return UpdateStatus.model_validate(result)

    async def residency(self) -> ResidencyDetail:
        """
        Residency
        What each engine holds in memory, how big it is and when it expires.
        """
        result = await self._fetch("/residency", method="GET")
        return ResidencyDetail.model_validate(result)

    async def openapi(self) -> OpenApiDocument:
        """
        Self-description
        This API as an OpenAPI 3.1 document, describing the core that serves it.
        """
        result = await self._fetch("/openapi.json", method="GET")
        return OpenApiDocument.model_validate(result)

    async def engines(self) -> list[EngineSummary]:
        """
        Engines
        Every declared engine, running or not, with its code and weights licences.
        """
        result = await self._fetch("/engines", method="GET")
        return _ENGINES_RESPONSE.validate_python(result)

    async def engine_capabilities(self, engine: str) -> EngineCapabilities200Response | EngineCapabilities404Response | EngineCapabilities503Response:
        """
        Engine capabilities
        What the engine can do with the variant it has loaded, and what its other variants could.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/capabilities", method="GET", response_kind="auto", expect_statuses=(404, 503))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": Capabilities.model_validate(result) }

    async def engine_voices(self, engine: str) -> EngineVoices200Response | EngineVoices404Response:
        """
        Voices
        The engine's voices, built in and cloned.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices", method="GET", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": _ENGINE_VOICES_RESPONSE_200.validate_python(result) }

    async def create_voice(self, engine: str, body: dict[str, Any]) -> CreateVoice201Response | CreateVoice400Response | CreateVoice403Response | CreateVoice404Response | CreateVoice422Response:
        """
        Create a voice
        Creates a voice from a reference, such as a clip to clone, or from a blend of voices the engine has.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices", method="POST", body=body, content_type="multipart/form-data", body_kind="multipart", response_kind="auto", expect_statuses=(400, 403, 404, 422))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 201, "content_type": "application/json", "data": Voice.model_validate(result) }

    async def delete_voice(self, engine: str, voice: str) -> DeleteVoice204Response | DeleteVoice400Response | DeleteVoice403Response | DeleteVoice404Response | DeleteVoice422Response:
        """
        Delete a voice
        Deletes a voice.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices/{quote(str(voice), safe='')}", method="DELETE", response_kind="auto", expect_statuses=(400, 403, 404, 422))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 204 }

    async def voice_preview(self, engine: str, voice: str) -> VoicePreview200Response | VoicePreview404Response:
        """
        Voice preview
        A short sample of the voice.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices/{quote(str(voice), safe='')}/preview", method="GET", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "audio/wav", "data": result }

    async def speak(self, body: EngineSpeakRequest) -> Speak200Response | Speak400Response | Speak404Response | Speak422Response | Speak429Response | Speak503Response:
        """
        Speak
        Speaks a line with one engine, streamed or as a finished file.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/speak", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 404, 422, 429, 503))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 429:
            return { "status": 429, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _content_type == "audio/mpeg":
            return { "status": 200, "content_type": "audio/mpeg", "data": result }
        if _content_type == "audio/opus":
            return { "status": 200, "content_type": "audio/opus", "data": result }
        if _content_type == "audio/flac":
            return { "status": 200, "content_type": "audio/flac", "data": result }
        if _content_type == "audio/l16":
            return { "status": 200, "content_type": "audio/l16", "data": result }
        return { "status": 200, "content_type": "audio/wav", "data": result }

    async def dialogue(self, engine: str, body: EngineDialogueRequest) -> Dialogue200Response | Dialogue400Response | Dialogue404Response | Dialogue422Response | Dialogue429Response | Dialogue503Response:
        """
        Dialogue
        A conversation between speakers in one take, on a variant that declares dialogue.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/dialogue", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 404, 422, 429, 503))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 429:
            return { "status": 429, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _content_type == "audio/mpeg":
            return { "status": 200, "content_type": "audio/mpeg", "data": result }
        if _content_type == "audio/opus":
            return { "status": 200, "content_type": "audio/opus", "data": result }
        if _content_type == "audio/flac":
            return { "status": 200, "content_type": "audio/flac", "data": result }
        if _content_type == "audio/l16":
            return { "status": 200, "content_type": "audio/l16", "data": result }
        return { "status": 200, "content_type": "audio/wav", "data": result }

    async def catalog(self) -> list[CatalogEntry]:
        """
        Catalog
        Every engine this core knows how to install, with both licences, before anything is installed.
        """
        result = await self._fetch("/catalog", method="GET")
        return _CATALOG_RESPONSE.validate_python(result)

    async def uninstall_engine(self, engine: str) -> UninstallEngine204Response | UninstallEngine403Response | UninstallEngine404Response | UninstallEngine409Response:
        """
        Uninstall an engine
        Removes an engine this API installed.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}", method="DELETE", response_kind="auto", expect_statuses=(403, 404, 409))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 204 }

    async def unload_engine(self, engine: str, query: UnloadEngineQuery | None = None) -> UnloadEngine200Response | UnloadEngine403Response | UnloadEngine404Response | UnloadEngine409Response:
        """
        Unload an engine
        Frees the engine's model now, rather than waiting out its keep-alive.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/unload", method="POST", response_kind="auto", expect_statuses=(403, 404, 409), params=query)
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": EngineSummary.model_validate(result) }

    async def install_engine(self, engine: str, query: InstallEngineQuery | None = None) -> InstallEngine202Response | InstallEngine400Response | InstallEngine403Response | InstallEngine404Response | InstallEngine409Response:
        """
        Install an engine
        Installs an engine from the catalog, as a job to follow.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/install", method="POST", response_kind="auto", expect_statuses=(400, 403, 404, 409), params=query)
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 202, "content_type": "application/json", "data": InstallJob.model_validate(result) }

    async def reinstall_engine(self, engine: str, query: ReinstallEngineQuery | None = None) -> ReinstallEngine202Response | ReinstallEngine400Response | ReinstallEngine403Response | ReinstallEngine404Response | ReinstallEngine409Response:
        """
        Reinstall an engine
        Rebuilds an installed engine beside the old one and swaps it in once it works.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/reinstall", method="POST", response_kind="auto", expect_statuses=(400, 403, 404, 409), params=query)
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 202, "content_type": "application/json", "data": InstallJob.model_validate(result) }

    async def pull_engine(self, engine: str, body: PullRequest) -> PullEngine202Response | PullEngine403Response | PullEngine404Response | PullEngine409Response:
        """
        Pull weights
        Downloads a variant's weights ahead of its first load, as a job to follow.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/pull", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(403, 404, 409))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 202, "content_type": "application/json", "data": InstallJob.model_validate(result) }

    async def install_jobs(self) -> InstallJobs200Response | InstallJobs403Response:
        """
        Install jobs
        Every install job, running and finished.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/installs", method="GET", response_kind="auto", expect_statuses=(403,))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": _INSTALL_JOBS_RESPONSE_200.validate_python(result) }

    async def reinstall_outdated(self) -> ReinstallOutdated202Response | ReinstallOutdated403Response:
        """
        Reinstall outdated engines
        Reinstalls every engine an upgrade left behind.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/installs/outdated", method="POST", response_kind="auto", expect_statuses=(403,))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 202, "content_type": "application/json", "data": ReinstallOutdated.model_validate(result) }

    async def install_job(self, job: str) -> InstallJob200Response | InstallJob403Response | InstallJob404Response:
        """
        Install job
        One install job and where it has got to.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/installs/{quote(str(job), safe='')}", method="GET", response_kind="auto", expect_statuses=(403, 404))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": InstallJob.model_validate(result) }

    async def install_job_events(self, job: str) -> InstallJobEvents200Response | InstallJobEvents403Response | InstallJobEvents404Response:
        """
        Install job events
        An install job's progress and output as server-sent events.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/installs/{quote(str(job), safe='')}/events", method="GET", response_kind="auto", expect_statuses=(403, 404))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "text/event-stream", "data": result }

    async def settings(self) -> Settings200Response | Settings403Response:
        """
        Settings
        Every setting, its value, where the value came from and whether a change applies now.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/settings", method="GET", response_kind="auto", expect_statuses=(403,))
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": Settings.model_validate(result) }

    async def update_settings(self, body: SettingsPatch) -> UpdateSettings200Response | UpdateSettings400Response | UpdateSettings403Response | UpdateSettings404Response | UpdateSettings409Response | UpdateSettings422Response:
        """
        Update settings
        Changes settings in one transaction, and answers the whole document after the write.
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/settings", method="PATCH", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 403, 404, 409, 422))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 403:
            return { "status": 403, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 409:
            return { "status": 409, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": Settings.model_validate(result) }
