# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from urllib.parse import quote
from typing import Any, Literal, TypedDict
from pydantic import TypeAdapter
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_rhapsode_types import Capabilities, CoreHealth, CreateVoiceForm, EngineSpeakRequest, EngineSummary, ErrorBody, Voice


class EngineCapabilities200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: Capabilities


class EngineCapabilities404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class EngineCapabilities503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


class EngineVoices200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json"]
    data: list[Voice]


class EngineVoices404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice201Response(TypedDict):
    status: Literal[201]
    content_type: Literal["application/json"]
    data: Voice


class CreateVoice404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class CreateVoice422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class DeleteVoice204Response(TypedDict):
    status: Literal[204]


class DeleteVoice404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class VoicePreview200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav"]
    data: bytes


class VoicePreview404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["audio/wav", "audio/mpeg", "audio/opus", "audio/flac", "audio/l16"]
    data: bytes


class Speak400Response(TypedDict):
    status: Literal[400]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak422Response(TypedDict):
    status: Literal[422]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak429Response(TypedDict):
    status: Literal[429]
    content_type: Literal["application/json"]
    data: ErrorBody


class Speak503Response(TypedDict):
    status: Literal[503]
    content_type: Literal["application/json"]
    data: ErrorBody


_ENGINES_RESPONSE: TypeAdapter[list[EngineSummary]] = TypeAdapter(list[EngineSummary])
_ENGINE_VOICES_RESPONSE_200: TypeAdapter[list[Voice]] = TypeAdapter(list[Voice])


class RhapsodePublicClient(BaseClient):

    async def health(self) -> CoreHealth:
        """
        The core's own. It answers while every worker is down and never blocks on one, because a
        """
        result = await self._fetch("/health", method="GET")
        return CoreHealth.model_validate(result)

    async def engines(self) -> list[EngineSummary]:
        """
        Every declared engine, whether or not it is running. Never spawns one: this is the list an
        """
        result = await self._fetch("/engines", method="GET")
        return _ENGINES_RESPONSE.validate_python(result)

    async def engine_capabilities(self, engine: str) -> EngineCapabilities200Response | EngineCapabilities404Response | EngineCapabilities503Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/capabilities", method="GET", response_kind="auto", expect_statuses=(404, 503))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": Capabilities.model_validate(result) }

    async def engine_voices(self, engine: str) -> EngineVoices200Response | EngineVoices404Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices", method="GET", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "application/json", "data": _ENGINE_VOICES_RESPONSE_200.validate_python(result) }

    async def create_voice(self, engine: str, body: dict[str, Any]) -> CreateVoice201Response | CreateVoice404Response | CreateVoice422Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices", method="POST", body=body, content_type="multipart/form-data", body_kind="multipart", response_kind="auto", expect_statuses=(404, 422))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 201, "content_type": "application/json", "data": Voice.model_validate(result) }

    async def delete_voice(self, engine: str, voice: str) -> DeleteVoice204Response | DeleteVoice404Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices/{quote(str(voice), safe='')}", method="DELETE", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 204 }

    async def voice_preview(self, engine: str, voice: str) -> VoicePreview200Response | VoicePreview404Response:
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/engines/{quote(str(engine), safe='')}/voices/{quote(str(voice), safe='')}/preview", method="GET", response_kind="auto", expect_statuses=(404,))
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        return { "status": 200, "content_type": "audio/wav", "data": result }

    async def speak(self, body: EngineSpeakRequest) -> Speak200Response | Speak400Response | Speak404Response | Speak422Response | Speak429Response | Speak503Response:
        """
        The one endpoint that matters. Cues the effective variant does not claim are stripped
        """
        _status, _content_type, result, _response_headers = await self._fetch_full("/speak", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), response_kind="auto", expect_statuses=(400, 404, 422, 429, 503))
        if _status == 400:
            return { "status": 400, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 422:
            return { "status": 422, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 429:
            return { "status": 429, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _status == 503:
            return { "status": 503, "content_type": "application/json", "data": ErrorBody.model_validate(result) }
        if _content_type == "audio/mpeg":
            return { "status": 200, "content_type": "audio/mpeg", "data": result }
        if _content_type == "audio/opus":
            return { "status": 200, "content_type": "audio/opus", "data": result }
        if _content_type == "audio/flac":
            return { "status": 200, "content_type": "audio/flac", "data": result }
        if _content_type == "audio/l16":
            return { "status": 200, "content_type": "audio/l16", "data": result }
        return { "status": 200, "content_type": "audio/wav", "data": result }
