# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from typing import Any
from pydantic import BaseModel

class ApiInfo(BaseModel):
    title: str
    # The running core's package version. Not the contract.
    version: str

# This file, `rhapsode.types.ck` and `rhapsode.openai.ck` as OpenAPI 3.1. protocol.md § 9. Only the
# top of the document is declared: the rest is OpenAPI's own shape, and a client that wants it typed
# already has a library that types it.
class OpenApiDocument(BaseModel):
    openapi: str
    info: ApiInfo
    paths: dict[str, Any]
    components: dict[str, Any] | None = None
