# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field

class Dial(BaseModel):
    # Inclusive.
    min: float
    # Inclusive.
    max: float
    # What the engine uses when the request says nothing.
    default: float

class Cloning(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    supported: bool
    # [min, max] of usable reference audio.
    reference_seconds: list[float] | None = Field(alias="referenceSeconds", default=None)
    # File types a `reference` may be. § 7.
    formats: list[str] | None = None

# Whether a create may carry a `blend` recipe instead of a `reference`. § 7.
class Blending(BaseModel):
    supported: bool

class Streaming(BaseModel):
    supported: bool
    granularity: Literal["chunk", "sentence"] | None = None

class NativeFormat(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # v1 accepts pcm_s16le and nothing else.
    encoding: str
    sample_rate: int = Field(alias="sampleRate")
    channels: int

class EngineIdentity(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str = Field(alias="displayName")
    adapter_version: str = Field(alias="adapterVersion")
    upstream_version: str | None = Field(alias="upstreamVersion", default=None)

# Code and weights separately, because the weights licence is the one package metadata never reveals
# and the one that decides whether a commercial user may ship. A scanner reads the package, reports
# the code licence, and is wrong in the way that matters.
class License(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    code: str
    weights: str
    weights_commercial_use: bool = Field(alias="weightsCommercialUse")
    notes: str | None = None

class Device(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    type: Literal["cuda", "rocm", "mps", "cpu"]
    name: str
    vram_bytes: int | None = Field(alias="vramBytes", default=None)

class Voice(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    label: str
    description: str | None = None
    # Opaque. Changes whenever the rendering would. Never parse it.
    spec: str
    tags: list[str] | None = None
    # Worker-scoped; the core rewrites it on the way out.
    preview_url: str | None = Field(alias="previewUrl", default=None)

class CreateVoiceForm(BaseModel):
    id: str
    label: str | None = None
    # Exactly one of `reference` and `blend`. § 7.
    reference: bytes | None = None
    # A recipe, `name(weight)+name(weight)`, over voices the engine has.
    blend: str | None = None

class SpeakRequest(BaseModel):
    text: str
    voice: str | None = None
    # Absent means whatever is loaded.
    variant: str | None = None
    format: Literal["wav", "mp3", "opus", "flac", "pcm"] | None = None
    # From the effective variant's `languages`.
    language: str | None = None
    # Closed, and deliberately has no word for "ordinary".
    delivery: Literal["hushed", "frantic"] | None = None
    # Validated against the effective variant's dials.
    params: dict[str, float] | None = None
    seed: int | None = None
    stream: bool | None = None

class LoadRequest(BaseModel):
    variant: str | None = None

# Required, unlike a load's: there is no "whatever is loaded" to fall back on for weights that are
# not loaded yet. protocol.md § 8.
class FetchRequest(BaseModel):
    variant: str

# `retryable` is a field rather than something the client infers from the status, because the
# distinction that matters is between "this request was wrong" and "this request was fine and the
# server was not". A caller that conflates them either retries a permanent failure forever or
# discards work that would have succeeded on the next pass.
class ErrorDetail(BaseModel):
    # A closed set that § 9 grows at the end. A reader that meets a code from a newer contract must
    # not lose the envelope over it: `message` and `retryable` are the two fields that decide what
    # the caller does next, and they parse fine. The core falls back to `internal` for the code and
    # keeps the rest, rather than reporting a parse failure in place of the real error.
    code: Literal["bad_request", "unknown_engine", "unknown_voice", "unsupported", "model_unavailable", "oom", "overloaded", "internal", "forbidden", "conflict"]
    message: str
    retryable: bool

class WorkerHealth(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    process: Literal["up", "draining"]
    model: Literal["unloaded", "loading", "loaded", "unloading"]
    variant: str | None = None
    device: str | None = None
    vram_bytes: int | None = Field(alias="vramBytes", default=None)

class ResidencySummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    resident: int
    max: int
    waiting: int
    # Named, because a wait at maxResidentModels 1 looks exactly like a hang.
    blocked_by: str | None = Field(alias="blockedBy", default=None)

class PullRequest(BaseModel):
    # Absent means the engine's default variant.
    variant: str | None = None

# One event on a job's stream, `GET /installs/{job}/events`. The shape is ServerKit's server feed,
# declared here so a client can parse it without depending on ServerKit.
class FeedProgress(BaseModel):
    # The job's step.
    phase: str
    index: int
    total: int
    status: Literal["running", "done", "failed"]

# What one build of an engine can perform. Capabilities depend on which build is loaded, which is
# the whole reason this document has two levels: chatterbox `turbo` performs the paralinguistic
# tags and discards the dials, while `original` is the other way round.
class Variant(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # A subset of the standard vocabulary, § 5.
    cues: list[str]
    # Ditto. Not an enum: § 9 forbids failing on an unknown one.
    deliveries: list[str]
    # Engine-specific numbers, named by the adapter.
    dials: dict[str, Dial]
    languages: list[str] | None = None
    # Overrides the engine's own ceiling for this build.
    max_characters: int | None = Field(alias="maxCharacters", default=None)
    # Optional only because contract 1 shipped without it. § 4.
    cloning: Cloning | None = None
    # Beside cloning, for the same reason: it needs no model. § 7.
    blending: Blending | None = None

class EngineSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str = Field(alias="displayName")
    license: License
    process: Literal["down", "starting", "up", "draining", "failed"]
    model: Literal["unloaded", "loading", "loaded", "unloading"]
    variant: str | None = None
    last_error: str | None = Field(alias="lastError", default=None)
    restarts: int

# What exists, installed or not. `/engines` is what this box has; this is what it could have, with
# both licences, because the weights licence is only worth reading before the install.
class CatalogEntry(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    display_name: str = Field(alias="displayName")
    license: License
    # The Python distribution the installer installs.
    package: str
    default_variant: str | None = Field(alias="defaultVariant", default=None)
    installed: Literal["no", "installing", "yes"]
    # Installed through the API, so removable by it.
    managed: bool

class EngineSpeakRequest(SpeakRequest):
    engine: str

class ErrorBody(BaseModel):
    error: ErrorDetail

class InstallJob(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    engine: str
    kind: Literal["install", "pull"]
    # What a pull fetches, or an install fetches in step 5.
    variant: str | None = None
    state: Literal["queued", "running", "succeeded", "failed"]
    step: Literal["venv", "packages", "verify", "register", "weights"] | None = None
    # ISO 8601, UTC.
    created_at: str = Field(alias="createdAt")
    started_at: str | None = Field(alias="startedAt", default=None)
    finished_at: str | None = Field(alias="finishedAt", default=None)
    # Present exactly when `state` is `failed`.
    error: ErrorDetail | None = None

class FeedEvent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # The Last-Event-ID resume key.
    id: int
    ts: str
    source: str
    level: Literal["debug", "info", "warn", "error"]
    kind: Literal["progress", "status", "log", "error", "heartbeat"]
    message: str | None = None
    # The job id.
    correlation_id: str | None = Field(alias="correlationId", default=None)
    progress: FeedProgress | None = None
    data: Any | None = None

# The resident build, and everything true only while it is resident. Absent from the capability
# document entirely when nothing is loaded, because a worker in up(unloaded) has nothing to
# describe and an invented answer is worse than no answer.
class CurrentVariant(Variant):
    model_config = ConfigDict(populate_by_name=True)

    variant: str
    cloning: Cloning
    # Absent means no, so a worker that predates it is read correctly.
    blending: Blending | None = None
    streaming: Streaming
    native_format: NativeFormat = Field(alias="nativeFormat")

class CoreHealth(BaseModel):
    contract: int
    status: Literal["ok", "degraded"]
    engines: list[EngineSummary]
    residency: ResidencySummary

class Capabilities(BaseModel):
    # The contract major this worker settled on. § 9.
    contract: int
    engine: EngineIdentity
    license: License
    device: Device
    current: CurrentVariant | None = None
    variants: dict[str, Variant]
    # What this worker can actually encode, here and now.
    formats: list[str]
