# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, ConfigDict, Field

class ApiInfo(BaseModel):
    title: str
    # The running core's package version. Not the contract.
    version: str

class SettingsServer(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    port: int
    host: str
    shutdown_grace_ms: int = Field(alias="shutdownGraceMs")

class SettingsLog(BaseModel):
    level: Literal["error", "warn", "info", "debug", "trace"]

class SettingsResidency(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    max_resident_models: int = Field(alias="maxResidentModels")
    eviction_wait_seconds: int = Field(alias="evictionWaitSeconds")
    keep_alive_seconds: int = Field(alias="keepAliveSeconds")

class SettingsWorkers(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    socket_dir: str = Field(alias="socketDir")
    voice_dir: str = Field(alias="voiceDir")
    startup_timeout_seconds: int = Field(alias="startupTimeoutSeconds")
    drain_grace_ms: int = Field(alias="drainGraceMs")
    max_restarts: int = Field(alias="maxRestarts")
    restart_decay_seconds: int = Field(alias="restartDecaySeconds")

class SettingsInstall(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    venv_dir: str = Field(alias="venvDir")
    # Absent when there is neither a setting nor a checkout to find.
    source_dir: str | None = Field(alias="sourceDir", default=None)
    python: str

class SettingsManagement(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # Never the token itself, which is a root password for the box.
    token_set: bool = Field(alias="tokenSet")
    origins: list[str]

class SettingsUpdate(BaseModel):
    check: bool

class SettingsEngine(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    # Absent when the engine uses residency.keepAliveSeconds.
    keep_alive_seconds: int | None = Field(alias="keepAliveSeconds", default=None)

class SettingField(BaseModel):
    # Dotted: residency.keepAliveSeconds, engines.kokoro.keepAliveSeconds.
    key: str
    # The layer the value in use came from.
    source: Literal["default", "config", "database"]
    # Whether a change takes effect when it is written.
    applies: Literal["live", "restart"]
    # A value waiting for a restart. For management.token, `true` and never the token.
    saved: Any | None = None

# This file, `rhapsode.types.ck` and `rhapsode.openai.ck` as OpenAPI 3.1. protocol.md § 9. Only the
# top of the document is declared: the rest is OpenAPI's own shape, and a client that wants it typed
# already has a library that types it.
class OpenApiDocument(BaseModel):
    openapi: str
    info: ApiInfo
    paths: dict[str, Any]
    components: dict[str, Any] | None = None

# What the running process is using. A setting waiting for a restart shows its old value here.
class SettingsValues(BaseModel):
    server: SettingsServer
    log: SettingsLog
    residency: SettingsResidency
    workers: SettingsWorkers
    install: SettingsInstall
    management: SettingsManagement
    update: SettingsUpdate
    # One per engine in the registry.
    engines: dict[str, SettingsEngine]

class Settings(BaseModel):
    values: SettingsValues
    fields: list[SettingField]
